server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/foragesb-db?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: user
    password: user
    driverClassName: com.mysql.cj.jdbc.Driver
  application:
    name: spring-forage

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true


info:
  application:
    name: forage-app
    version: '@project.version@'